### ISSUE TITLE
can not compile with typescript > 2.7

### ISSUE THREAD

**Issue by Richard-Mathie** [thegecko/webusb#5]
there is some change with the type api in typescript 2.7 such that lodash types do not compile

```
node_modules/@types/lodash/index.d.ts(12651,53): error TS2344: Type 'T' does not satisfy the constraint 'object'.
```

see similar issues here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23375

I'll add a constraint to the `package.json`

**Comment by aj-r** [comment]
Looks like this has been fixed in the latest version of lodash (4.14.103). Try running `npm install -S @types/lodash@latest` (or similar in yarn) with TS 2.7, and see if that fixes it.

**Comment by thegecko** [comment]
Fixed in #8 I believe
