### PR TITLE
Constrain typescript to <2.7 Fixes #5

### LINKED ISSUE #5: can not compile with typescript > 2.7
there is some change with the type api in typescript 2.7 such that lodash types do not compile

```
node_modules/@types/lodash/index.d.ts(12651,53): error TS2344: Type 'T' does not satisfy the constraint 'object'.
```

see similar issues here: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/23375

I'll add a constraint to the `package.json`

### PR DESCRIPTION
**Pull request by Richard-Mathie**

### CODE REVIEW

**Comment by Richard-Mathie** [comment]
incidentally I get a lot of complaints from npm that gulp-util,  is depreciated, ect

```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
npm WARN deprecated graceful-fs@3.0.11: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: please upgrade to graceful-fs 4 for compatibility with current and future versions of Node.js
```

I see that the only package still requiring it is `gulp-tslint` but they are working on an update.

**Comment by thegecko** [comment]
Hi @Richard-Mathie. Many apologies I didn't notice your PR and have since fixed this by pinning TypeScript to 2.6. Are you happy for me to close this PR?

**Comment by thegecko** [comment]
Fixed in #8
